# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51afdb029275d18eacc14bb8b8a646a2dbf974d2f7efdb5e6371764bc324f062faffdebf3322f923d8ab8a7343c1844251d97567754b324b60feabdfcd71482a

test:
  secret_key_base: bfaa8a9aac9872355553b05ecf3e9398b387a364e1e5eac9b3bc5e3eedf35551cd44d3d9548af2631f22430abd1f750dad24a04829d850c17a6f3f24a34e4d1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
